# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Garrett Kelly
email: boontdustie@gmail.com
description: "At the intersection of weird technology / low power fm (lpfm) / ruby on rails / outsider music / fashion blogging / paranormal encounters / revolution / and emacs, I guess"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://garrettkelly.xyz" # the base hostname & protocol for your site
twitter_username: boontdustie
github_username:  boontdustie

# Misc
google_verification: null

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

# Build settings
markdown: kramdown
